### ISSUE TITLE
Additional options for journalbeat.yml generation

### ISSUE THREAD

**Issue by nilshee** [rolehippie/journalbeat#19]
For the graylog ingestion to work properly, some further options are required for output.logstash like slow_start and bulk_max_size.
In the current template this is not possible. 

c.f. https://go2docs.graylog.org/current/getting_in_log_data/ingest_journald.html

**Comment by tboerger** [comment]
@nilshee what do you think about https://github.com/rolehippie/journalbeat/pull/20 as a solution?

**Comment by nilshee** [comment]
It looks fine to me, but I can't test it anymore.

I received a lot of Go errors and switched to filebeat since journalbeat is deprecated. So, I'm not using the role anymore.

**Comment by tboerger** [comment]
And which role are you using for filebeat?

**Comment by nilshee** [comment]
https://github.com/geerlingguy/ansible-role-filebeat

I can't use your role since it doesn't support the SSL config options for logstash (I realized I have to use a non-DMZ network for log transport and therefore need authentication and encryption).

**Comment by tboerger** [comment]
Solved via https://github.com/rolehippie/journalbeat/pull/20
